import turtle as t

# 2 squares next to each other
# t.forward(50)
# t.left(90)
# t.forward(50)
# t.left(90)
# t.forward(50)
# t.left(90)
# t.forward(50)
# t.left(90)
# t.penup()
# t.forward(100)
# t.pendown()
# t.forward(50)
# t.left(90)
# t.forward(50)
# t.left(90)
# t.forward(50)
# t.left(90)
# t.forward(50)

# Yellow house with red tiles
# t.fillcolor("red")
# t.begin_fill()
# t.goto(100, 0)
# t.goto(50, 100)
# t.goto(0, 0)
# t.end_fill()
# t.left(-90)
# t.fillcolor("yellow")
# t.begin_fill()
# t.goto(0, -100)
# t.goto(100, -100)
# t.goto(100, 0)
# t.end_fill()

# Hexagon with orange border
# t.pensize(7)
# t.pencolor("orange")
# t.fillcolor("green")
# t.begin_fill()
# t.forward(100)
# t.left(60)
# t.forward(100)
# t.left(60)
# t.forward(100)
# t.left(60)
# t.forward(100)
# t.left(60)
# t.forward(100)
# t.left(60)
# t.forward(100)
# t.end_fill()

# Red heart with black border
t.pencolor("Black")
t.pensize(7)
t.fillcolor("red")
t.begin_fill()
t.left(45)
t.forward(90)
t.right(45)
t.forward(50)
t.right(45)
t.forward(50)
t.left(90)
t.forward(50)
t.right(45)
t.forward(50)
t.right(45)
t.forward(90)
t.right(45)
t.forward(35)
t.right(45)
t.forward(210)
t.right(90)
t.forward(210)
t.right(45)
t.forward(35)
t.end_fill()

t.exitonclick()